name: laravel

networks:
  default:
    driver: bridge

services:
  app:
    container_name: laravel-app
    image: ghcr.io/mdonnyirwansyah/laravel:latest
    restart: unless-stopped
    ports:
      - "8001:80"
    networks:
      - default
