---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: laravel-app
  namespace: laravel
spec:
  encryptedData:
    APP_KEY: AgDD3ah+599e8/8rrsaea53FtxtKk6iPv2uMyot+904DUav5vtJYmXMPmzMRnNEokaT05CDkwC3mMWi90UbmBjoiTRbnohjsQjRn72G/BD6b3p5RYXnXI/g4MXUIEFXdVkOUFiNgzXGPGHWR2sPVRenSTrzxrdjhKOWYhwxS3wvajD4QX5GiyxFbZQxthbMfYgGxonsJWWjjnqeNGEGf/a7GmcFa3s/T7fLeotGNZpuF8MiIO6JOjTgWi/SmcKFBgQUcv2d7cUPaY0ZHx7f3ZkK9bRXEw3A4OSnt0e/iwmXv9wVMvGwdlNKYPIEbxz76e0/VFXYDHxiYQdsSu7PLj8Rnjq5p+CLJ0ROIhePcNSaDtw24/dHRFc9rPt7bY0aHbnyWCD8Ji4Om1JjEyP20O0V+DDxBhhgcjU/NO8M0mQrboZFlvxI5F9wKZXpmDZIdUeyqOH2QvRKlE5OD2VSyNNmnmLK6RdQ3W0Pt8Z16lxylvwVUDg9Tas9tku/S8A8mbYgLYx/MiePy5ARsHz66RdlCrRdvgKmSU0oyIUoCyo3aCihoOgxE8coIEIU2bLwpHQuSK8vlW59OkHmqZvbr4NPZmkEq7abblv7wEKkJB0R+ecIUQx9t+jVquuhLJqGp7by/1gsidLDkieAFb6nXT51yoUut5RUoBJT7RZx3csqMoFjVjrrOITK+1Uz4EY/Xhgd91sBY8QL31+HAt8eo1vxA1jWckPOsFMede9u8leTMKKiAk3Sl4TYJXZ6LDoLS8caSL5s=
  template:
    metadata:
      creationTimestamp: null
      name: laravel-app
      namespace: laravel
    type: Opaque
