apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migrate
  namespace: laravel
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/mdonnyirwansyah/laravel:latest-arm64
          imagePullPolicy: IfNotPresent
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: laravel-app
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-app
                  key: APP_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-db
                  key: POSTGRES_PASSWORD
